name: Keep Codespace Alive

on:
  schedule:
    # Jalankan setiap 20 menit
    - cron: '*/20 * * * *'
  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual

jobs:
  ping-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Keep codespace alive using GitHub API
        env:
          GH_TOKEN: ${{ secrets.CODESPACE_PAT }}
          CODESPACE_NAME: "redesigned-yodel-x55rpq69jjj4h6jp6"
          GITHUB_USER: "JepriiGans"
        run: |
          echo "Attempting to keep codespace alive using GitHub API..."
          
          # Dapatkan informasi tentang codespace
          echo "Getting codespace information..."
          CODESPACE_INFO=$(curl -s -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/user/codespaces" | jq '.[] | select(.name=="'$CODESPACE_NAME'")')
          
          echo "Codespace info:"
          echo "$CODESPACE_INFO" | jq '.'
          
          # Dapatkan status codespace
          CODESPACE_STATE=$(echo "$CODESPACE_INFO" | jq -r '.state')
          echo "Codespace state: $CODESPACE_STATE"
          
          # Jika codespace tidak aktif, coba aktifkan
          if [ "$CODESPACE_STATE" != "running" ] && [ "$CODESPACE_STATE" != "idle" ]; then
            echo "Codespace is not running. Attempting to start it..."
            
            # Coba start codespace menggunakan API
            START_RESPONSE=$(curl -s -X POST \
              -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/user/codespaces/$CODESPACE_NAME/start")
            
            echo "Start response:"
            echo "$START_RESPONSE" | jq '.'
            
            # Tunggu beberapa saat agar codespace mulai
            echo "Waiting for codespace to start..."
            sleep 30
          fi
          
          # Ping codespace dengan mengakses URL
          echo "Pinging codespace URL..."
          CODESPACE_URL="https://$CODESPACE_NAME.github.dev/"
          curl -s -I "$CODESPACE_URL" || echo "Failed to ping codespace URL"
          
          # Alternatif: Gunakan GitHub API untuk melakukan ping
          echo "Pinging codespace using GitHub API..."
          PING_RESPONSE=$(curl -s \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/user/codespaces/$CODESPACE_NAME")
          
          echo "Ping response:"
          echo "$PING_RESPONSE" | jq '.'
          
          echo "Codespace ping completed." 
